version: "3.8"

volumes:
  bank_queue_tickets_web_mysql_db:
    driver: local

services:
  mysql:
    image: mysql:8.0
    container_name: bank_queue_tickets_mysql
    volumes:
      - ./database.sql:/database.sql
      - bank_queue_tickets_web_mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    ports:
      - "3306:3306"

  web:
    build: ./.docker
    container_name: bank_queue_tickets_web
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - mysql
